global using AutoFixture;
global using FluentAssertions;
global using Microsoft.Data.Sqlite;
global using Microsoft.EntityFrameworkCore;
global using Moq;
global using NUnit.Framework;
global using OneCampus.Infrastructure.Repositories;
global using OneCampus.Infrastructure.Tests.Helpers;
global using Database = OneCampus.Infrastructure.Data.Entities;
global using OneCampusDbContext = OneCampus.Infrastructure.Data.OneCampusDbContext;
