---
name: Build and Push Image to AWS ECR
on:
  push:
    branches: [ development ]
jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      run: |
         aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 866681751834.dkr.ecr.eu-west-3.amazonaws.com
    - name: Build, Tag, and Push the Image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: 866681751834.dkr.ecr.eu-west-3.amazonaws.com
        ECR_REPOSITORY: onecampus-api
        IMAGE_TAG: latest
      run: |
        cd OneCampus
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
