name: CI

on:
  pull_request:   # Add this section
    branches:
      - main
  push:
    branches:
      - development

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.309

    - name: Change directory
      run: cd ES6WebApi
    
    - name: Restore dependencies
      run: |
            cd ES6WebApi
            dotnet restore

    - name: Test
      run: |
            cd ES6WebApi
            dotnet test
    
    - name: Build
      run: |
            cd ES6WebApi
            dotnet build
