name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.309

    - name: Change directory
      run: cd OneCampus
    
    - name: Restore dependencies
      run: |
            cd OneCampus
            dotnet restore

    - name: Test
      run: |
            cd OneCampus
            dotnet test
    
    - name: Build
      run: |
            cd OneCampus
            dotnet build
